version: '3.8'

services:
  nginx:                        # ok
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./docker/nginx/nginx.conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html/
    ports:
      - 8080:80
    depends_on:
      - php
    networks:
      - net-frontend

  php:                          # build ok
    image: legrizzly/php-custom:3.0.2
    container_name: php
    volumes:
      - ./www:/var/www/html/
    networks:
      - net-frontend
      - net-backend

  composer:                     # build ok
    image: legrizzly/composer-custom:1.0.2
    container_name: composer
    volumes:
      - ./www:/var/www
    # command: "composer --version"
    # command: ["composer require phpmailer/phpmailer"]

networks:
  net-frontend:
    name: front-web
  net-backend:
    name: back-db

